
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author binh3920
 */
public class EditFrame extends javax.swing.JFrame {
    private Dictionary myDict;
    /**
     * Creates new form EditFrame
     */
    public EditFrame() {
        initComponents();
    }
    
    public EditFrame(Dictionary myDict) {
        this.myDict = myDict;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        slangInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        defInput = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        javax.swing.JRadioButton add = new javax.swing.JRadioButton();
        duplicate = new javax.swing.JRadioButton();
        editSlangButton = new javax.swing.JButton();
        EditSlang = new javax.swing.JRadioButton();

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setText("Slang");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Andale Mono", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 186, 182));
        jLabel1.setText("Edit a Slang");

        jLabel3.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel3.setText("Slang");

        slangInput.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        slangInput.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        slangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slangInputActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel4.setText("New word");

        defInput.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        defInput.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel5.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel5.setText("Type");

        buttonGroup1.add(add);
        add.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        add.setSelected(true);
        add.setText("Add");
        add.setActionCommand("add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        buttonGroup1.add(duplicate);
        duplicate.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        duplicate.setText("Remove");
        duplicate.setActionCommand("remove");
        duplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicateActionPerformed(evt);
            }
        });

        editSlangButton.setBackground(new java.awt.Color(12, 158, 158));
        editSlangButton.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        editSlangButton.setForeground(new java.awt.Color(255, 255, 255));
        editSlangButton.setText("Submit");
        editSlangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSlangButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(EditSlang);
        EditSlang.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        EditSlang.setText("Edit");
        EditSlang.setActionCommand("edit");
        EditSlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditSlangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(add)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(slangInput, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                        .addComponent(defInput))
                                    .addComponent(duplicate)
                                    .addComponent(EditSlang)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(editSlangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(106, 106, 106)))
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(slangInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(defInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duplicate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditSlang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editSlangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slangInputActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addActionPerformed

    private void duplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duplicateActionPerformed

    private void editSlangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSlangButtonActionPerformed
        String slang = slangInput.getText().toLowerCase();
        String definition = defInput.getText().toLowerCase();
        int slangLength = slang.length();
        int defLength = definition.length();
        String type = buttonGroup1.getSelection().getActionCommand();

        if (slangLength == 0 || defLength == 0) {
            JOptionPane.showMessageDialog(null, "Wrong input!");
        } else {
            if (!myDict.contains(slang)) {
                JOptionPane.showMessageDialog(null, "Slang is not exists!");
            } else {
                List<String> listDef = myDict.getValue(slang);
                if ("add".equals(type)) {
                    if (!myDict.addDef(slang, definition)) {
                        JOptionPane.showMessageDialog(null, "Definition already exists!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Add definition success!");
                    }
                } else if ("remove".equals(type)) {
                    if (!myDict.removeDef(slang, definition)) {
                        JOptionPane.showMessageDialog(null, "Definition does not exists!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Remove definition success!");
                    }
                } else {
                    myDict.editSlang(slang, definition);
                    JOptionPane.showMessageDialog(null, "Edit slang success!");
                }
            }
        }
    }//GEN-LAST:event_editSlangButtonActionPerformed

    private void EditSlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditSlangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditSlangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EditSlang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField defInput;
    private javax.swing.JRadioButton duplicate;
    private javax.swing.JButton editSlangButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField slangInput;
    // End of variables declaration//GEN-END:variables
}
