package mypackage;


import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author binh3920
 */
public class AddFrame extends javax.swing.JFrame {
    private Dictionary myDict;
    /**
     * Creates new form AddFrame
     */
    public AddFrame() {
        initComponents();
    }
    
    public AddFrame(Dictionary myDict) {
        this.myDict = myDict;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        slangInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        defInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        overwrite = new javax.swing.JRadioButton();
        duplicate = new javax.swing.JRadioButton();
        addSlangButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Slang");

        jLabel1.setFont(new java.awt.Font("Andale Mono", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(110, 186, 182));
        jLabel1.setText("Add new Slang");

        jLabel2.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel2.setText("Slang");

        slangInput.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        slangInput.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));
        slangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slangInputActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel3.setText("Definition");

        defInput.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        defInput.setBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLabel4.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        jLabel4.setText("If exists");

        buttonGroup1.add(overwrite);
        overwrite.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        overwrite.setSelected(true);
        overwrite.setText("Overwrite");
        overwrite.setActionCommand("overwrite");
        overwrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overwriteActionPerformed(evt);
            }
        });

        buttonGroup1.add(duplicate);
        duplicate.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        duplicate.setText("Duplicate");
        duplicate.setActionCommand("duplicate");
        duplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duplicateActionPerformed(evt);
            }
        });

        addSlangButton.setBackground(new java.awt.Color(12, 158, 158));
        addSlangButton.setFont(new java.awt.Font("Andale Mono", 0, 18)); // NOI18N
        addSlangButton.setForeground(new java.awt.Color(255, 255, 255));
        addSlangButton.setText("Submit");
        addSlangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSlangButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(slangInput)
                            .addComponent(defInput)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(duplicate)
                                    .addComponent(overwrite))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSlangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(slangInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(defInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(overwrite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(duplicate)
                .addGap(18, 18, 18)
                .addComponent(addSlangButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        overwrite.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slangInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slangInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slangInputActionPerformed

    private void overwriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overwriteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overwriteActionPerformed

    private ArrayList<String> convertToList(String definition) {
        ArrayList<String> listWords = new ArrayList<>();
        while(true) {
            int pos = definition.indexOf(",");
            if (pos == -1) {
                listWords.add(definition);
                return listWords;
            } else {
                listWords.add(definition.substring(0, pos));
                definition = definition.substring(pos+2);
            }
        }
    }
    private void addSlangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSlangButtonActionPerformed
        String slang = slangInput.getText().toLowerCase();
        String definition = defInput.getText().toLowerCase();
        int slangLength = slang.length();
        int defLength = definition.length();
        String type = buttonGroup1.getSelection().getActionCommand();
        
        if (slangLength == 0 || defLength == 0) {
            JOptionPane.showMessageDialog(null, "Wrong input!");
        } else {
            ArrayList<String> listDef = convertToList(definition);
            if (!myDict.contains(slang)) {
                myDict.addSlang(slang, listDef);
            } else {
                if ("overwrite".equals(type)) {
                    myDict.addSlangOverwrite(slang, listDef);
                } else {
                    myDict.addSlangDuplicate(slang, listDef);
                }
            }
            JOptionPane.showMessageDialog(null, "Add new slang success!");
        }
    }//GEN-LAST:event_addSlangButtonActionPerformed

    private void duplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duplicateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duplicateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSlangButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField defInput;
    private javax.swing.JRadioButton duplicate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton overwrite;
    private javax.swing.JTextField slangInput;
    // End of variables declaration//GEN-END:variables

}
